# Establecer la imagen base
FROM python:3.9

# Establecer el directorio de trabajo en el contenedor
WORKDIR /VIRTUAL_TRENDS

# Copiar el archivo de requerimientos e instalar dependencias
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Instalar Django
#RUN pip install django
# Instala Django y djangorestframework
RUN pip install django==3.9 djangorestframework==3.13


# Copiar el resto de los archivos al directorio de trabajo en el contenedor
COPY . .

# Exponer el puerto en el que se ejecuta la aplicación Django
EXPOSE 8000

# Comando para ejecutar la aplicación Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]