FROM python:3.10.4-alpine3.15

#esta linea es la que permite ver el log como si se estuvuiera ejecutando en nuestra compu
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apk update  \
&& apk add --no-cache gcc musl-dev postgresql-dev python3-dev libffi-dev \
&& pip install --upgrade pip

COPY ./requirements.txt ./

RUN pip install -r requirements.txt

COPY ./ ./

#CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"] 
CMD ["sh", "entrypoint.sh"]

# el ultimo argumento es necesario para compartir puerto